var annotated_dup =
[
    [ "boss_config_t", "structboss__config__t.html", null ],
    [ "boss_projectile_t", "structboss__projectile__t.html", null ],
    [ "boss_t", "structboss__t.html", null ],
    [ "Bouton", "structBouton.html", null ],
    [ "Entite", "structEntite.html", null ],
    [ "EntreeRespawn", "structEntreeRespawn.html", null ],
    [ "item_", "structitem__.html", null ],
    [ "Mob", "structMob.html", null ],
    [ "ObjetInteractif", "structObjetInteractif.html", null ],
    [ "p3_cell_t", "structp3__cell__t.html", null ],
    [ "Perso", "structPerso.html", null ],
    [ "SaveData", "structSaveData.html", null ],
    [ "SonCache", "structSonCache.html", null ],
    [ "SpawnPoint", "structSpawnPoint.html", null ],
    [ "t_Animation", "structt__Animation.html", null ],
    [ "t_case", "structt__case.html", null ],
    [ "t_console_cmd", "structt__console__cmd.html", null ],
    [ "t_Cuisson", "structt__Cuisson.html", null ],
    [ "t_objectif", "structt__objectif.html", null ],
    [ "t_objectifs", "structt__objectifs.html", null ],
    [ "tile_", "structtile__.html", null ],
    [ "TileRef", "structTileRef.html", null ],
    [ "tileset_", "structtileset__.html", null ]
];